version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: ../.docker/backend/Dockerfile
    container_name: cicd-backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_VERSION=1.0.0
      - CORS_ORIGIN=https://todonest.id.vn
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend service  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../.docker/frontend/Dockerfile
    container_name: cicd-frontend
    ports:
      - "3001:80"
    restart: always
    environment:
      - VITE_API_URL=${API_URL:-https://todonest.id.vn/api}
    depends_on:
      - backend
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: cicd-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge